{
 "title": "Docker Swarm Node Monitoring",
 "tags": [
  "Node exporter",
  "cAdvisor",
  "Prometheus",
  "Docker Swarm"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "interval", "label": "Interval", "query": "30s,1m,2m,5m,10m,30m,1h,6h,12h" },
   {
    "name": "instance_ip",
    "label": "Instance IP",
    "query": "label_values(scrape_duration_seconds,instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "Node association",
   "type": "table",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "node_meta{instance=~\"$instance_ip\"}"
    }
   ]
  },
  {
   "title": "CPU usage overview (Host and Container)",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu{mode=\"idle\",instance=~\"$instance_ip\"}[$interval])) *100)",
     "legendFormat": "node {{instance}} overall"
    },
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{name=~\".+\",instance=~\"$instance_ip\"}[$interval])) by (name) *25",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "RAM usage overview (Host and Container)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal{instance=~\"$instance_ip\"} - node_memory_MemAvailable{instance=~\"$instance_ip\"} ",
     "legendFormat": "node {{instance}} overall"
    },
    {
     "expr": "container_memory_rss{instance=~\"$instance_ip\",name!=\"\"}",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}